apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app-deployment
spec:
  replicas: 2 # Start with 2 replicas
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - name: nodejs-app
        image: 108726286568.dkr.ecr.us-east-1.amazonaws.com/docker/my-nodejs-app:latest # Use a consistent tag like 'latest' or use the GitHub SHA variable in the pipeline config
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"

